# action.yml
name: 'Build Jenkins job'
description: 'Trigger jenkins job'
inputs:
  jenkins-url:
    description: 'Jenkins server url whithout http://'
    required: true
  jenkins-token:
    description: 'Jenkins token to access jenkins server'
    required: true
  jenkins-token-name:
    description: 'Jenkins token name to trigger job build'
    required: true
  jenkins-user:
    description: "Jenkins user name"
    required: true
  job-path:
    description: 'job/folder_name/job/job_name'
    required: true
  job-params:
    description: "params to run the job. JSON string. i.e '{\"param1\": \"value1\", \"param2\": \"value2\"}' "
    required: false
outputs:
  job_status:
    description: 'Build status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jenkins-url}}
    - ${{ inputs.jenkins-token}}
    - ${{ inputs.jenkins-token-name}}
    - ${{ inputs.jenkins-user}}
    - ${{ inputs.job-path }}
    - ${{ inputs.job-params}}
branding:
  icon: 'arrow-right-circle'
  color: 'blue'
